apps:
  argocd:
    name: argo 
    namespace: argocd
    source:
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.31.0
  litmus:
    name: litmus
    namespace: litmus
    source:
      repoURL: https://github.com/Feederhigh5/master-thesis-poc.git
      path: litmus
      targetRevision: main
destination:
    server: https://kubernetes.default.svc
