apps:
  argocd:
    name: argo 
    namespace: argocd
    source:
      chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.31.0
  litmus:
    name: litmus
    namespace: litmus
    source:
      chart: litmus
      repoURL: https://litmuschaos.github.io/litmus-helm/
      targetRevision: 2.15.10
  prometheus:
    name: prometheus
    namespace: prometheus
    source:
      chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 22.6.0
destination:
    server: https://kubernetes.default.svc
