apps:
  argocd:
    name: argo 
    namespace: argocd
    source:
      chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.31.0
  elasticSearch:
    name: elastic-search
    namespace: logging
    source:
      chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
  kibana:
    name: kibana
    namespace: logging
    source:
      chart: kibana
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
  fluentd:
    name: fluentd
    namespace: logging
    source:
      chart: fluentd
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.4.3
  linkerdCrds:
    name: linkerd-crds 
    namespace: linkerd
    source:
      chart: linkerd-crds
      repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.6.1 
  linkerdControlPlane:
    name: linkerd-control-plane
    namespace: linkerd
    source:
      chart: linkerd-control-plane
      repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.12.3
  litmus:
    name: litmus
    namespace: litmus
    source:
      chart: litmus
      repoURL: https://litmuschaos.github.io/litmus-helm/
      targetRevision: 2.15.10
  prometheus:
    name: prometheus
    namespace: prometheus
    source:
      chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 22.6.0
  grafana:
    name: grafana
    namespace: prometheus
    source:
      chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.56.4
  cAdvisor:
    name: cadvisor
    namespace: cadvisor
    source:
      chart: cadvisor
      repoURL: https://ckotzbauer.github.io/helm-charts
      targetRevision: 2.2.4
destination:
    server: https://kubernetes.default.svc
logging: true
