apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userservice
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: frontend
# spec:
#   behavior:
#     scaleUp:
#       stabilizationWindowSeconds: 0
#       policies:
#         - type: Percent
#           value: 100
#           periodSeconds: 5
#       selectPolicy: Max
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: frontend
#   minReplicas: 5
#   maxReplicas: 25
#   metrics:
#     - type: External
#       external:
#         metric:
#           name: loadbalancing.googleapis.com|https|request_count
#           selector:
#             matchLabels:
#               resource.labels.forwarding_rule_name: FORWARDING_RULE_NAME
#         target:
#           type: AverageValue
#           averageValue: "5"
# ---

# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: example-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: example-app
#   minReplicas: 1
#   maxReplicas: 100
#   metrics:
#   - type: Pods
#     pods:
#       metric:
#         name: response_latency_seconds_per_second
#       target:
#         type: AverageValue
#         averageValue: 0.1

# rules:
# - seriesQuery: 'response_latency_seconds_sum{namespace!="",pod!="",service="my-service"}'
#   resources:
#     overrides:
#       namespace: {resource: "namespace"}
#       pod: {resource: "pod"}
#   name:
#     matches: "^(.*)_total"
#     as: "${1}_per_second"
#   metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
