apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pod
  namespace: prometheus
spec:
  replicas: 0
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: false
        runAsUser: 65534
      containers:
        - name: debug-pod
          image: centos:latest
          command: ["/bin/sh"]
          args: ["-ec", "while :; do echo .; sleep 5;done"]
          volumeMounts:
            - name: datadir
              mountPath: "/bitnami/mongodb"
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: prometheus-server
