apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pod
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      containers:
        - name: debug-pod
          image: centos:latest
          command: ["/bin/sh"]
          args: ["-ec", "while :; do echo .; sleep 5;done"]
          volumeMounts:
            - name: datadir0
              mountPath: "/volume/0"
            - name: datadir1
              mountPath: "/volume/1"
            - name: datadir2
              mountPath: "/volume/2"
      volumes:
        - name: datadir0
          persistentVolumeClaim:
            claimName: elasticsearch-master-elasticsearch-master-0
        - name: datadir1
          persistentVolumeClaim:
            claimName: elasticsearch-master-elasticsearch-master-1
        - name: datadir2
          persistentVolumeClaim:
            claimName: elasticsearch-master-elasticsearch-master-2
