apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-elastics
  labels:
    app: elasticsearch
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/pv-storage/pv0001/elastics