apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-grafana
  labels:
    app: grafana
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv-storage/pv0001/grafana