apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: litmus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    argocd.argoproj.io/instance: litmus
    helm.sh/chart: mongodb-12.1.11
  name: litmus-mongodb
  namespace: litmus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv0001-litmus