apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-litmus
  labels:
    app: litmus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/pv-storage/pv0001/litmus