apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/pv-storage/pv0001/prometheus